Console.ForegroundColor = ConsoleColor.Blue;
Console.WriteLine("Vento no Litoral");
Console.ForegroundColor = ConsoleColor.White;

Console.WriteLine("De tarde eu quero descansar");
Console.WriteLine("Chegar até a praia e ver");
Console.WriteLine("Se o vento ainda está forte, vai");
Console.WriteLine("Ser bom subir nas pedras, sei");
Console.WriteLine("Que faço isso pra esquecer");
Console.WriteLine("Eu deixo a onda me acertar");
Console.ForegroundColor = ConsoleColor.Blue;
Console.WriteLine("E o vento vai levando tudo embora");
Console.ForegroundColor = ConsoleColor.White;
Console.WriteLine("Agora está tão longe, vê");
Console.WriteLine("A linha do horizonte me distrai");
Console.WriteLine("Dos nossos planos é que tenho mais saudade");
Console.WriteLine("Quando olhávamos juntos na mesma direção");
Console.WriteLine("Aonde está você agora");
Console.WriteLine("Além de aqui dentro de mim?");
Console.WriteLine("Agimos certo sem querer");
Console.WriteLine("Foi só o tempo que errou");
Console.WriteLine("Vai ser difícil eu sem você");
Console.WriteLine("Porque você está comigo o tempo todo");
Console.WriteLine("E quando vejo o mar");
Console.WriteLine("Existe algo que diz");
Console.WriteLine("Que a vida continua e se entregar é uma bobagem");
Console.WriteLine("Já que você não está aqui");
Console.WriteLine("O que posso fazer é cuidar de mim");
Console.WriteLine("Quero ser feliz ao menos");
Console.WriteLine("Lembra que o plano era ficarmos bem?");
Console.WriteLine("Ei, olha só o que eu achei, hmm");
Console.WriteLine("Cavalos-marinhos");
Console.WriteLine("Sei que faço isso pra esquecer");
Console.WriteLine("Eu deixo a onda me acertar");
Console.WriteLine("E o vento vai levando tudo embora");